server:
  port: 9200
spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.100:8848
        namespace: public
        username: nacos
        password: nacos
        metadata:
          zone: dev