server:
  port: 9301
spring:
  application:
    name: provider-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.100:8848
        namespace: public
        username: nacos
        password: nacos
        metadata:
          zone: local
