spring:
  application:
    name: sentinel-service
  cloud:
    sentinel:
      transport:
        dashboard: http://192.168.1.43:8080
        port: 8719
        client-ip: 192.168.1.43
      web-context-unify: false
